name: Waka Readme

on:
  workflow_dispatch:        # Allow manual trigger
  schedule:
    - cron: "0 0 * * *"     # Runs every day at midnight UTC
    # - cron: "30 18 * * *" # Example: run daily at 6:30 PM UTC

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: WakaTime Readme
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          SHOW_TOTAL: true


# v2
# name: Waka Readme

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

# jobs:
#   update-readme:
#     name: Update WakaTime Stats
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: WakaTime Readme
#         uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           SHOW_TITLE: true
#           TIME_RANGE: last_7_days
#           SHOW_TOTAL: true

#       - name: Commit & Push changes
#         run: |
#           git config user.name "sarthakbhatele"
#           git config user.email "153352714+sarthakbhatele@users.noreply.github.com"
#           git add .
#           git commit -m "Updated WakaTime stats"
#           git push

# v3
# name: Waka Readme

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: WakaTime Readme (no auto-commit)
#         uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           SHOW_TITLE: true
#           TIME_RANGE: last_7_days
#           SHOW_TOTAL: true
#           COMMIT_MESSAGE: ""   # 👈 disables auto-commit

#       - name: Commit & Push changes (as you)
#         run: |
#           git config user.name "sarthakbhatele"
#           git config user.email "153352714+sarthakbhatele@users.noreply.github.com"
#           git add .
#           git commit -m "Updated WakaTime stats" || echo "No changes to commit"
#           git push

# #v4 
# name: Waka Readme

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"   # Runs daily at midnight

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Update WakaTime stats
#         uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           SHOW_TITLE: true
#           TIME_RANGE: last_7_days
#           SHOW_TOTAL: true
#           COMMIT_MESSAGE: ""   # Disable auto-commit by bot

#       - name: Commit & Push (only if changed)
#         run: |
#           git config user.name "sarthakbhatele"
#           git config user.email "153352714+sarthakbhatele@users.noreply.github.com"
#           if git diff --quiet; then
#             echo "✅ No changes to commit"
#           else
#             git add .
#             git commit -m "Updated WakaTime stats"
#             git push
#           fi

# v5
# name: Waka Readme

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs every day at 12 AM UTC
#   workflow_dispatch:     # Allows you to manually trigger the update

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}    # Add this line
